esphome:
  name: cat-feeder

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

stepper:
  - platform: uln2003
    id: cat_feeder
    pin_a: D1
    pin_b: D3
    pin_c: D2
    pin_d: D4
    max_speed: 250 steps/s
    sleep_when_done: true
    acceleration: inf
    deceleration: inf

switch:
  - platform: template
    id: feed_cat
    name: "Feed Cat"
    turn_on_action:
      - switch.template.publish:
          id: feed_cat
          state: ON
      - stepper.report_position:
          id: cat_feeder
          position: 0
      - stepper.set_target:
          id: cat_feeder
          target: 40
      - switch.template.publish:
          id: feed_cat
          state: OFF

time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        hours: /6
        then:
          - switch.turn_on: feed_cat
