esphome:
  name: cat-feeder

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

stepper:
  - platform: uln2003
    id: feed_stepper
    pin_a: D1
    pin_b: D3
    pin_c: D2
    pin_d: D4
    max_speed: 250 steps/s
    sleep_when_done: true
    acceleration: inf
    deceleration: inf

button:
  - platform: template
    id: feed_button
    name: "Feed"
    on_press:
      then:
        - stepper.report_position:
            id: feed_stepper
            position: 0
        - stepper.set_target:
            id: feed_stepper
            target: 40

time:
  - platform: homeassistant
    on_time:
      - cron: "* * /6 * * *"
        then:
          - button.press: feed_button
